// SKAI team content. Edit this file to update the Team page.
window.SKAI_DATA = window.SKAI_DATA || {};
window.SKAI_DATA.team = [

  {name:'Andrea Jesús Cimmino Arriaga',photo:'assets/images/andrea-cimmino.jpg',initials:'AC',pi:true,roleEs:'Profesor Permanente Laboral',roleEn:'Associate Professor',office:'1101',email:'andreajesus.cimmino@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)',scholar:'https://scholar.google.es/citations?user=_6U9WMcAAAAJ&hl=es&oi=ao',linkedin:'https://www.linkedin.com/in/andrea-cimmino-arriaga-64b6b9112',orcid:'https://orcid.org/0000-0002-1823-4484',portal:'https://portalcientifico.upm.es/es/ipublic/researcher/307657'},
  {name:'Joaquín Gayoso Cabada',photo:'assets/images/joaquin-gayoso.jpg',initials:'JG',roleEs:'Profesor Contratado Doctor',roleEn:'Associate Professor',office:'1105',email:'j.gayoso@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)',portal:'https://portalcientifico.upm.es/es/ipublic/researcher/333052', scholar:'https://scholar.google.es/citations?user=6sm-GZAAAAAJ&hl=es&oi=ao', linkedin:'https://www.linkedin.com/in/joaquin-gayoso-cabada-a5023530',orcid:'https://orcid.org/0000-0002-1304-469X'},
  {name:'Jessica Díaz Fernández', photo:'assets/images/jessica-diaz.jpeg', initials:'JD',roleEs:'Profesora Titular de Universidad',roleEn:'Associate Professor',office:'1119',email:'yesica.diaz@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)', scholar:'https://scholar.google.es/citations?user=TNcH2uUAAAAJ&hl=es&oi=ao', portal:'https://portalcientifico.upm.es/es/ipublic/researcher/309450', linkedin:'https://www.linkedin.com/in/jessica-diaz-fernandez-1a519616/'},
  {name:'Virginia Díaz Barcos',photo:'assets/images/virginia-diaz.jpeg',initials:'VD',roleEs:'Profesora Contratada Doctora',roleEn:'Associate Professor',office:'Ed. B · planta 3',email:'virginia.diaz@upm.es',departmentEs:'Química y Tecnología de Alimentos',departmentEn:'Food Chemistry and Technology',schoolEs:'ETS de Ingeniería Agronómica, Alimentaria y de Biosistemas (ETSIAAB)',schoolEn:'School of Agricultural, Food and Biosystems Engineering (ETSIAAB)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)',portal:'https://portalcientifico.upm.es/es/ipublic/researcher/308852'},
  {name:'Rodrigo Mariño Andrés',photo:'assets/images/rodrigo-marino.jpg',initials:'RM',roleEs:'Profesor Permanente Laboral',roleEn:'Associate Professor',office:'4411',email:'rodrigo.marino@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)', scholar:'https://scholar.google.es/citations?user=jY17GykAAAAJ&hl=es&oi=sra', linkedin:'https://www.linkedin.com/in/rodrigo-mari%C3%B1o-andr%C3%A9s-7b8618126/', orcid:'https://orcid.org/0000-0002-9699-3398', portal:'https://portalcientifico.upm.es/es/ipublic/researcher/308009'},
  {name:'María Navas Loro',photo:'assets/images/maria-navas.jpg',initials:'MN',roleEs:'Profesora Ayudante Doctora',roleEn:'Assistant Professor',office:'4120',email:'m.navas@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)',scholar:'https://scholar.google.com/citations?user=rshakekAAAAJ&hl=es',portal:'https://portalcientifico.upm.es/es/ipublic/researcher/311561', orcid:'https://orcid.org/0000-0003-1011-5023', linkedin:'https://www.linkedin.com/in/mnavasloro'},
  {name:'Enrique Gutiérrez Álvarez',initials:'EG',roleEs:'Profesor Permanente Laboral',roleEn:'Associate Professor',office:'2003',email:'enrique.gutierrez.alvarez@upm.es',departmentEs:'Matemática Aplicada a las TIC (MATIC)',departmentEn:'Applied Mathematics to ICT (MATIC)',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)', portal:'https://portalcientifico.upm.es/es/ipublic/researcher/335868'},
  {name:'Sergio Gil Borrás',photo:'assets/images/sergio-gil.jpeg',initials:'SG',roleEs:'Profesor Permanente Laboral',roleEn:'Associate Professor',office:'4211',email:'sergio.gil@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)',portal:'https://portalcientifico.upm.es/es/ipublic/researcher/332149'},
  {name:'José Carlos Gamazo Real', photo:'assets/images/jc-gamazo.jpeg',initials:'JG',roleEs:'Profesor Permanente Laboral',roleEn:'Associate Professor',office:'4307',email:'josecarlos.gamazo@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)', portal:'https://portalcientifico.upm.es/es/ipublic/researcher/332873'},
  {name:'Javier García Martín',photo:'assets/images/javier-garcia.jpg',initials:'JG',roleEs:'Profesor Titular de Universidad',roleEn:'Associate Professor',office:'4418',email:'javier.garciam@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)', portal:'https://portalcientifico.upm.es/es/ipublic/researcher/309353'},
  {name:'Jorge Enrique Pérez Martínez',photo:'assets/images/jorge-enrique-perez.jpg',initials:'JP',roleEs:'Profesor Titular de Universidad',roleEn:'Associate Professor',office:'4416',email:'jorgeenrique.perez@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)',portal:'https://portalcientifico.upm.es/es/ipublic/researcher/304998', linkedin:'https://es.linkedin.com/in/jorge-enrique-p%C3%A9rez-mart%C3%ADnez-a833219b'},
  {name:'Javier Alegre Landaburu',initials:'JA',roleEs:'Estudiante de doctorado',roleEn:'PhD Student',office:'SKAI Laboratory',email:'javier.alegre.landaburu@upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)'},
  {name:'Borzou Ghorbani',initials:'CA',roleEs:'Estudiante de doctorado',roleEn:'PhD Student',office:'SKAI Laboratory',email:'borzou.ghorbani@alumnos.upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)'},
  {name:'Covadonga Arias Fernández',initials:'CA',roleEs:'Estudiante de máster',roleEn:'Master\'s Student',office:'SKAI Laboratory',email:'covadonga.arias@alumnos.upm.es',departmentEs:'Sistemas Informáticos',departmentEn:'Computer Systems',schoolEs:'ETS de Ingeniería de Sistemas Informáticos (ETSISI)',schoolEn:'School of Computer Systems Engineering (ETSISI)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)'},
  {name:'Dana Annette Meyer',initials:'DM',roleEs:'Estudiante de grado',roleEn:'Bachelor Student',office:'SKAI Laboratory',email:'annette.meyer@upm.es',departmentEs:'Inteligencia Artificial',departmentEn:'Artificial Intelligence',schoolEs:'ETS de Ingenieros Informáticos (ETSIINF)',schoolEn:'School of Computer Science (ETSIINF)',universityEs:'Universidad Politécnica de Madrid (UPM)',universityEn:'Universidad Politécnica de Madrid (UPM)'}
];
